apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-config
  namespace: {{ .Release.Namespace }}
data:
  permissive_traffic_policy_mode: {{ .Values.OpenServiceMesh.enablePermissiveTrafficPolicy | default "false" | quote }}
  egress: {{ .Values.OpenServiceMesh.enableEgress | quote }}
  envoy_log_level: {{ .Values.OpenServiceMesh.envoyLogLevel | quote }}
  prometheus_scraping: "true"

{{- if .Values.OpenServiceMesh.zipkinEndpoint.enable }}
  zipkin_tracing: {{ .Values.OpenServiceMesh.zipkinEndpoint.enable | quote }}
  zipkin_address: {{ .Values.OpenServiceMesh.zipkinEndpoint.address | quote }}
  zipkin_port: {{ .Values.OpenServiceMesh.zipkinEndpoint.port | quote }}
  zipkin_endpoint: {{ .Values.OpenServiceMesh.zipkinEndpoint.endpoint | quote }}
{{- end }}

{{- if .Values.OpenServiceMesh.enableEgress }}
  mesh_cidr_ranges: {{ .Values.OpenServiceMesh.meshCIDRRanges | quote }}
{{- end }}
  use_https_ingress: {{ .Values.OpenServiceMesh.useHTTPSIngress | default "false" | quote }}
