apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-config
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
data:
  permissive_traffic_policy_mode: {{ .Values.OpenServiceMesh.enablePermissiveTrafficPolicy | default "false" | quote }}
  egress: {{ .Values.OpenServiceMesh.enableEgress | quote }}
  envoy_log_level: {{ .Values.OpenServiceMesh.envoyLogLevel | quote }}
  envoy_image: {{ .Values.OpenServiceMesh.sidecarImage | quote }}
  init_container_image: "{{ .Values.OpenServiceMesh.image.registry }}/init:{{ .Values.OpenServiceMesh.image.tag }}"
  enable_privileged_init_container: {{ .Values.OpenServiceMesh.enablePrivilegedInitContainer | quote }}
  enable_debug_server: {{ .Values.OpenServiceMesh.enableDebugServer | quote }}
  prometheus_scraping: {{ .Values.OpenServiceMesh.enablePrometheusScraping | quote }}
  max_data_plane_connections: {{.Values.OpenServiceMesh.maxDataPlaneConnections | quote}}
  tracing_enable: {{ .Values.OpenServiceMesh.tracing.enable | quote }}
{{- if .Values.OpenServiceMesh.tracing.enable }}
  tracing_address: {{ include "osm.tracingAddress" . | quote }}
  tracing_port: {{ .Values.OpenServiceMesh.tracing.port | quote }}
  tracing_endpoint: {{ .Values.OpenServiceMesh.tracing.endpoint | quote }}
{{- end }}

  use_https_ingress: {{ .Values.OpenServiceMesh.useHTTPSIngress | default "false" | quote }}
  service_cert_validity_duration: {{ .Values.OpenServiceMesh.serviceCertValidityDuration | quote }}

{{- if .Values.OpenServiceMesh.outboundIPRangeExclusionList }}
  outbound_ip_range_exclusion_list: {{ join "," .Values.OpenServiceMesh.outboundIPRangeExclusionList | quote }}
{{- end}}

{{- if .Values.OpenServiceMesh.outboundPortExclusionList }}
  outbound_port_exclusion_list: {{ join "," .Values.OpenServiceMesh.outboundPortExclusionList | quote }}
{{- end}}

  proxy_limit_cpu: {{ .Values.OpenServiceMesh.injector.proxyResources.limits.cpu }}
  proxy_limit_memory: {{ .Values.OpenServiceMesh.injector.proxyResources.limits.memory }}
  proxy_requests_cpu: {{ .Values.OpenServiceMesh.injector.proxyResources.requests.cpu }}
  proxy_requests_memory: {{ .Values.OpenServiceMesh.injector.proxyResources.requests.memory }}
